name: Test build DS4MapperTest

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    env:
      test_version: 0.0.x.y

    steps:
    - uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    #- name: Setup nuget
    #  uses: nuget/setup-nuget@v2
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir build
      
    - name: Restore Packages
      run: nuget restore DS4MapperTest.sln

    - name: Build Solution
      run: |
        msbuild.exe DS4MapperTest.sln /p:DeleteExistingFiles=True /p:platform="x64" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DS4MapperTest_${{ env.test_version }}
        path: "${{ github.workspace }}\build"